title:         zman.io
description:   assorted scala utilities
logo:          logo.png
default_bg:    rummage.jpg
layouts:       ./_includes/_layouts
url:           "http://zman.io"
    
timezone:      America/Denver
permalink:     /posts/:categories/:title
paginate:      7
paginate_path: "page:num"
future:        false
pygments:      true
markdown:      redcarpet